### ISSUE TITLE
[Bug]: Stylesheet missing

### ISSUE THREAD

**Issue by CodeWithDennis** [vormkracht10/filament-2fa#11]
### What happened?

Since the package has been renamed, the stylesheet path in the class is wrong: `vendor/vormkracht10/filament-two-factor-auth/resources/dist/filament-two-factor-auth.css`. However, this might not be needed if you simply add the Blade files to the content array in the project's Tailwind config. You could include a readme in the package to guide users on adding that line to their file.

```js
import preset from '../../../../vendor/filament/filament/tailwind.config.preset'

export default {
    presets: [preset],
    content: [
        './app/Filament/**/*.php',
        './resources/views/filament/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
        './vendor/vormkracht10/filament-2fa/resources/**/*.blade.php'
    ],
}

```

### How to reproduce the bug

Add package to panel

### Package Version

1.1.5

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by Baspa** [comment]
Oops, that should be fixed in the latest version (v1.1.7).

**Comment by CodeWithDennis** [comment]
@Baspa Almost, you forgot to change the `viteTheme` in the TwoFactorAuthPlugin.php

```php
// L31
->viteTheme('vendor/vormkracht10/filament-two-factor-auth/resources/dist/filament-two-factor-auth.css')
```

to

// L31
->viteTheme('vendor/vormkracht10/filament-2fa/resources/dist/filament-two-factor-auth.css')
